version: "3"
services:
  metube:
    # Local Build: Use the following to build the Docker image locally
    build:
      context: .
      dockerfile: ./Dockerfile
    image: metube
    # Official Image: Comment out the lines above and uncomment the following line to use the official image
    # image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"

    # Example environment variables
    environment:
      # UID: 1000
      # GID: 1000
      YTDL_OPTIONS: '{"writesubtitles": true, "subtitleslangs": ["en", "-live_chat"], "postprocessors": [{"key": "FFmpegEmbedSubtitle", "already_have_subtitle": false}, {"key": "FFmpegMetadata", "add_chapters": true}]}'
      # Configure yt-dlp to download intermediary files to /temp
      TEMP_DIR: /temp

    volumes:
      - ./downloads:/downloads
      # Mount /temp using tmpfs
      # This will store the intermediary files in memory, making downloads faster; however, you won't be able to
      # resume a download if you stop the container
      - type: tmpfs
        target: /temp:rw,nosuid,nodev,exec
